pipeline:
  docker:
    group: docker-image
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kontena/pharos-kubelet-proxy-amd64
    dockerfile: Dockerfile
    auto_tag: true
    when:
      event: tag

  docker-arm:
    group: docker-image
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: kontena/pharos-kubelet-proxy-arm64
    dockerfile: Dockerfile.arm
    auto_tag: true
    when:
      event: tag
